-- create table pessoa (
-- id serial primary key,
-- nome varchar not null,
-- sobrenome varchar not null
-- );

-- create table dependente (
-- id serial primary key,
-- id_pessoa int references pessoa on delete cascade,
-- nome varchar not null,
-- sobrenome varchar not null
-- );
